=== atripunoska/BananaKeeper/BananaKeeper/bin/Debug/levels/BananaKeeperLev.dtd
<!-- ================== Banana Keeper ====================================== -->
<!ELEMENT BananaKeeperLevels (Title,LevelCollection)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT LevelCollection (Level+)>
<!ATTLIST LevelCollection                
                MaxWidth     CDATA #IMPLIED
                MaxHeight    CDATA #IMPLIED>

<!ELEMENT Level (L+)>
<!ATTLIST Level Id        CDATA #REQUIRED
                Width     CDATA #IMPLIED
                Height    CDATA #IMPLIED>

<!ELEMENT L (#PCDATA)>
<!ATTLIST L xml:space (default|preserve) 'preserve'>

<!-- ======================================================================= -->

=== atripunoska/BananaKeeper/BananaKeeper/bin/Debug/levels/Levels.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE BananaKeeperLevels SYSTEM "BananaKeeperLev.dtd">
<BananaKeeperLevels> 
  <Title>BananaKeeper</Title> 
  <LevelCollection MaxWidth="13" MaxHeight="11">
    <Level Id="BW1" Width="8" Height="8">
      <L>  ###</L>
      <L>  #.#</L>
      <L>  # ####</L>
      <L>###$ $.#</L>
      <L>#. $@###</L>
      <L>####$#</L>
      <L>   #.#</L>
      <L>   ###</L>
    </Level>
    <Level Id="BK2" Width="9" Height="9">
      <L>#####</L>
      <L>#@  #</L>
      <L># $$#=###</L>
      <L># $ #=#.#</L>
      <L>### ###.#</L>
      <L> ##    .#</L>
      <L> #   #  #</L>
      <L> #   ####</L>
      <L> #####</L>
    </Level>
    <Level Id="BK3" Width="10" Height="7">
      <L> #######</L>
      <L> #     ###</L>
      <L>##$###   #</L>
      <L># @ $  $ #</L>
      <L># ..# $ ##</L>
      <L>##..#   #</L>
      <L> ########</L>
    </Level>
    <Level Id="BK4" Width="6" Height="8">
      <L> ####</L>
      <L>##  #</L>
      <L>#@$ #</L>
      <L>##$ ##</L>
      <L>## $ #</L>
      <L>#.$  #</L>
      <L>#..*.#</L>
      <L>######</L>
    </Level>
    <Level Id="BK5" Width="8" Height="8">
      <L> ####</L>
      <L> #@ ###</L>
      <L> # $  #</L>
      <L>### # ##</L>
      <L>#.# #  #</L>
      <L>#.$  # #</L>
      <L>#.   $ #</L>
      <L>########</L>
    </Level>
    <Level Id="BK6" Width="13" Height="11">
      <L>   #######</L>
      <L>####     #</L>
      <L>#   .### #</L>
      <L># # #    ##</L>
      <L># # $ $#. #</L>
      <L># #  *  # #</L>
      <L># .#$ $ # #</L>
      <L>##    # # ###</L>
      <L> # ###.    @#</L>
      <L> #     ##   #</L>
      <L> ############</L>
    </Level>
    <Level Id="BK7" Width="10" Height="8">
      <L>   #######</L>
      <L>  ##  # @#</L>
      <L>  #   #  #</L>
      <L>  #$ $ $ #</L>
      <L>  # $##  #</L>
      <L>### $ # ##</L>
      <L>#.....  #</L>
      <L>#########</L>
    </Level>
    <Level Id="BK8" Width="10" Height="7">
      <L>   ######</L>
      <L> ###    #</L>
      <L>##. $## ##</L>
      <L>#..$ $  @#</L>
      <L>#.. $ $ ##</L>
      <L>######  #</L>
      <L>     ####</L>
    </Level>
    <Level Id="BK9" Width="11" Height="9">
      <L> #########</L>
      <L> #  ##   #</L>
      <L> #   $   #</L>
      <L> #$ ### $#</L>
      <L> # #...# #</L>
      <L>## #...# ##</L>
      <L># $  $  $ #</L>
      <L>#     # @ #</L>
      <L>###########</L>
    </Level>
    <Level Id="BK10" Width="8" Height="7">
      <L>  ######</L>
      <L>  #    #</L>
      <L>###$$$ #</L>
      <L>#@ $.. #</L>
      <L># $...##</L>
      <L>####  #</L>
      <L>   ####</L>
    </Level>
    <Level Id="BK11" Width="12" Height="6">
      <L> ####==#####</L>
      <L>##  #==#   #</L>
      <L># $ ####$  #</L>
      <L>#  $.... $ #</L>
      <L>##    # @ ##</L>
      <L> ##########</L>
    </Level>
    <Level Id="BK12" Width="8" Height="7">
      <L>  #####</L>
      <L>###  @#</L>
      <L>#  $. ##</L>
      <L>#  .$. #</L>
      <L>### *$ #</L>
      <L>  #   ##</L>
      <L>  #####</L>
    </Level>
    <Level Id="BK13" Width="8" Height="8">
      <L>  ####</L>
      <L>  #..#</L>
      <L> ## .##</L>
      <L> #  $.#</L>
      <L>## $  ##</L>
      <L>#  #$$ #</L>
      <L>#  @   #</L>
      <L>########</L>
    </Level>
    <Level Id="BK14" Width="8" Height="7">
      <L>########</L>
      <L>#  #   #</L>
      <L># $..$ #</L>
      <L>#@$.* ##</L>
      <L># $..$ #</L>
      <L>#  #   #</L>
      <L>########</L>
    </Level>
    <Level Id="BK15" Width="8" Height="7">
      <L> ######</L>
      <L>##    ##</L>
      <L># $ $$ #</L>
      <L>#......#</L>
      <L># $$ $ #</L>
      <L>### @###</L>
      <L>  ####</L>
    </Level>
    <Level Id="BK16" Width="10" Height="9">
      <L>  ######</L>
      <L>  #    ###</L>
      <L>  # $    #</L>
      <L>### $ ## #</L>
      <L>#... $   #</L>
      <L>#...$#$ ##</L>
      <L>#### # $ #</L>
      <L>   #  @  #</L>
      <L>   #######</L>
    </Level>
    <Level Id="BK17" Width="9" Height="7">
      <L>######</L>
      <L>#    #</L>
      <L># $$$##</L>
      <L>#  #..###</L>
      <L>##  ..$ #</L>
      <L> # @    #</L>
      <L> ########</L>
    </Level>
    <Level Id="BK18" Width="10" Height="9">
      <L>  ########</L>
      <L>  #   #. #</L>
      <L> ##  $...#</L>
      <L> #  $ #*.#</L>
      <L>## ##$# ##</L>
      <L>#   $  $ #</L>
      <L>#   #    #</L>
      <L>#######@ #</L>
      <L>      ####</L>
    </Level>
    <Level Id="BK19" Width="10" Height="8">
      <L> #######</L>
      <L> #.... #</L>
      <L>###...$###</L>
      <L>#  $#$ $ #</L>
      <L># $$  #$ #</L>
      <L>#    #   #</L>
      <L>#### @ ###</L>
      <L>   #####</L>
    </Level>
    <Level Id="BK20" Width="7" Height="8">
      <L>#######</L>
      <L>#..$..#</L>
      <L>#..#..#</L>
      <L># $$$ #</L>
      <L>#  $  #</L>
      <L># $$$ #</L>
      <L>#  #@ #</L>
      <L>#######</L>
    </Level>
    <Level Id="BK21" Width="11" Height="8">
      <L>   ######</L>
      <L>   # ...#</L>
      <L>####....#</L>
      <L>#  ###$ ###</L>
      <L># $ $  $$ #</L>
      <L>#@ $ $    #</L>
      <L>#   ###   #</L>
      <L>#####=#####</L>
    </Level>
    <Level Id="BK22" Width="9" Height="9">
      <L>########</L>
      <L>#      #</L>
      <L># #$$  #</L>
      <L># ...# #</L>
      <L>##...$ ##</L>
      <L> # ## $ #</L>
      <L> #$  $  #</L>
      <L> #  #  @#</L>
      <L> ########</L>
    </Level>
    <Level Id="BK23" Width="10" Height="8">
      <L>  #####</L>
      <L>###   ####</L>
      <L>#   $ $  #</L>
      <L># $   $ @#</L>
      <L>###$$#####</L>
      <L>  #  ..#</L>
      <L>  #....#</L>
      <L>  ######</L>
    </Level>
    <Level Id="BK24" Width="14" Height="9">
      <L>######===#####</L>
      <L>#    ###=#  .#</L>
      <L>#  $ $ #=#...#</L>
      <L># #  $ ###  .#</L>
      <L>#  $$$   $ @.#</L>
      <L>###  $  $#  .#</L>
      <L>  #  $#$ #...#</L>
      <L>  ##     #  .#</L>
      <L>   ###########</L>
    </Level>
    <Level Id="BK25" Width="11" Height="10">
      <L>     ######</L>
      <L> #####.   #</L>
      <L> #  #..## #</L>
      <L> #  $..   #</L>
      <L> #  # .# ##</L>
      <L>### ##$#  #</L>
      <L># $    $$ #</L>
      <L># #$#  #  #</L>
      <L>#@  #######</L>
      <L>#####</L>
    </Level>
    <Level Id="BK26" Width="13" Height="12">
      <L> #########</L>
      <L> #   ##  ####</L>
      <L> # $        #</L>
      <L> ##$### ##  #</L>
      <L> #  ## * # ##</L>
      <L> # $...... #</L>
      <L>## ### . # #</L>
      <L>#     $###$#</L>
      <L>#   #    $@#</L>
      <L>#####$# ####</L>
      <L>    #   #</L>
      <L>    #####</L>
    </Level>
    <Level Id="BK27" Width="15" Height="12">
      <L>      #########</L>
      <L>      #       #</L>
      <L>      # # # # #</L>
      <L>      #  $ $# #</L>
      <L>#######   $   #</L>
      <L>#..#  ## $ $# #</L>
      <L>#..   ## $ $  #</L>
      <L>#..#  ## ######</L>
      <L>#..# # $ $ #</L>
      <L>#..     $  #</L>
      <L>#  ### @ ###</L>
      <L>####=#####</L>
    </Level>
    <Level Id="BK28" Width="16" Height="13">
      <L>    ####</L>
      <L>#####  #</L>
      <L>#  $ $ #=#######</L>
      <L>#   $  #=#*.*.*#</L>
      <L>## $ $ ###.*.*.#</L>
      <L> #$ $  #  *.*.*#</L>
      <L> #@$ $    .*.*##</L>
      <L> #$ $  #  *.*.*#</L>
      <L>## $ $ ###.*.*.#</L>
      <L>#   $  #=#*.*.*#</L>
      <L>#  $ $ #=#######</L>
      <L>#####  #</L>
      <L>    ####</L>
    </Level>
    <Level Id="BK29" Width="9" Height="7">
      <L>########</L>
      <L>#......#</L>
      <L>#  $ # ##</L>
      <L># $ # $ #</L>
      <L>##$ $ $ #</L>
      <L> #  @   #</L>
      <L> ########</L>
    </Level>
    <Level Id="BK30" Width="12" Height="7">
      <L>  ##########</L>
      <L>###   .    #</L>
      <L>#   ##$##  #</L>
      <L># @$. . .$##</L>
      <L>## $##$## #</L>
      <L> #    .   #</L>
      <L> ##########</L>
    </Level>
    <Level Id="BK31" Width="9" Height="8">
      <L>   ######</L>
      <L>####.  @#</L>
      <L>#  $$$  #</L>
      <L>#.##.##.#</L>
      <L>#   $   #</L>
      <L>#  $.# ##</L>
      <L>####   #</L>
      <L>   #####</L>
    </Level>
    <Level Id="BK32" Width="8" Height="8">
      <L> ######</L>
      <L> #. ..#</L>
      <L> #. $.#</L>
      <L>###  $##</L>
      <L># $  $ #</L>
      <L># #$## #</L>
      <L>#   @  #</L>
      <L>########</L>
    </Level>
    <Level Id="BK33" Width="14" Height="12">
      <L>    ######</L>
      <L>  ###    ###</L>
      <L>  #   #$   ###</L>
      <L>  #   $   $$ #</L>
      <L>  # $$ #$    #</L>
      <L>  ##   $   $ #</L>
      <L>###### #$#####</L>
      <L>#..@ #$  #</L>
      <L>#.#..  $##</L>
      <L>#....$# #</L>
      <L>#....   #</L>
      <L>#########</L>
    </Level>
    <Level Id="BK34" Width="15" Height="13">
      <L>###############</L>
      <L>#      #      #</L>
      <L># $ #$ # $##$ #</L>
      <L># #  $ #      #</L>
      <L>#   ##$#$##$$ #</L>
      <L># # # ... #   #</L>
      <L># $  . # .$ # #</L>
      <L># $#@$...# #  #</L>
      <L>#    . # .  $ #</L>
      <L># ##.$###$. # #</L>
      <L># # $..... ## #</L>
      <L>#             #</L>
      <L>###############</L>
    </Level>
    <Level Id="BK35" Width="10" Height="10">
      <L>#########</L>
      <L>#   ##  #</L>
      <L># # $ $ #</L>
      <L>#  *.#  #</L>
      <L>## #.@.##</L>
      <L>##$###*###</L>
      <L>#        #</L>
      <L>#   ## # #</L>
      <L>######   #</L>
      <L>     #####</L>
    </Level>
    <Level Id="BK36" Width="15" Height="12">
      <L>########</L>
      <L>#      #</L>
      <L># $$   ###</L>
      <L>#  $ $$$ #####</L>
      <L>## ## ...    ##</L>
      <L> # #@#...###$ #</L>
      <L> # # $...     #</L>
      <L>## # $...$ # ##</L>
      <L>#  ##### ### #</L>
      <L>#      $   $ #</L>
      <L>###########  #</L>
      <L>          ####</L>
    </Level>
    <Level Id="BK37" Width="9" Height="8">
      <L>   #####</L>
      <L>   # @ #</L>
      <L>   #$$$#</L>
      <L>####   #</L>
      <L>#   .#$##</L>
